// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.firebears.subsystems;

import org.firebears.RobotMap;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class Lights extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    DigitalOutput line0 = RobotMap.lightsLine0;
    DigitalOutput line1 = RobotMap.lightsLine1;
    DigitalOutput line2 = RobotMap.lightsLine2;
    DigitalOutput line3 = RobotMap.lightsLine3;
    DigitalOutput line4 = RobotMap.lightsLine4;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    DriverStationLCD driverLCD = null;
    DriverStationLCD.Line displayLine = DriverStationLCD.Line.kUser1;

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
        driverLCD = DriverStationLCD.getInstance();
    }
    public static int SET_RED_ALLIANCE = 0;
    public static int SET_BLU_ALLIANCE = 1;
    public static int SHOOTER_WINDUP = 2;
    public static int SHOOT = 3;
    public static int DUMPING_FRISBEES = 4;
    public static int LOADER_ON_GROUND = 5;
    public static int MOVEING_FORWARD = 6;
    public static int MOVING_BACKWARD = 7;
    public static int FRISBEE_IN_BUCKET = 8;
    public static int NO_FRISBEE_IN_BUCKET = 9;
    public static int TARGET_IN_SIGHT = 10;
    public static int TARGET_NOT_IN_SIGHT = 11;
    public static int AUTO_TARGETING = 12;
    public static int CLIMBING = 13;
    public static int NO_CLIMB_SWITCHES_CLOSED = 14;
    public static int LEFT_CLIMB_SWITCH_CLOSED = 15;
    public static int RIGHT_CLIMB_SWITCH_CLOSED = 16;
    public static int AUTONOMOUS_STARTED = 17;
    public static int TELEOP_STARTED = 18;
    public static int END_OF_MATCH = 19;
    public static int FRISBEE_IN_LOADER = 20;
    public static int NO_FRISBEE_IN_LOADER = 21;

    public void lightProgram(int i) {
        System.out.println("lightProgram =" + i);
        if (i == SET_RED_ALLIANCE) {
            line0.set(false);
            line1.set(false);
            line2.set(false);
            line3.set(false);
            line4.set(false);
        }
        if (i == SET_BLU_ALLIANCE) {
            line0.set(true);
            line1.set(false);
            line2.set(false);
            line3.set(false);
            line4.set(false);
        }
        if (i == SHOOTER_WINDUP) {
            line1.set(true);
            line0.set(false);
            line2.set(false);
            line3.set(false);
            line4.set(false);
        }
        if (i == SHOOT) {
            line0.set(true);
            line1.set(true);
            line2.set(false);
            line3.set(false);
            line4.set(false);
        }
//        if (i == SHOOT) {
//            line4.set(true);
//            line3.set(true);
//            line2.set(false);
//            line0.set(false);
//            line1.set(false);
//        }
        if (i == DUMPING_FRISBEES) {
            line2.set(true);
            line0.set(false);
            line1.set(false);
            line3.set(false);
            line4.set(false);
        }
        if (i == LOADER_ON_GROUND) {
            line2.set(true);
            line0.set(true);
            line1.set(false);
            line3.set(false);
            line4.set(false);
        }
        if (i == MOVEING_FORWARD) {
            line1.set(true);
            line2.set(true);
            line0.set(false);
            line3.set(false);
            line4.set(false);
        }
        if (i == MOVING_BACKWARD) {
            line0.set(true);
            line1.set(true);
            line2.set(true);
            line3.set(false);
            line4.set(false);
        }
        if (i == FRISBEE_IN_BUCKET) {
            line3.set(true);
            line0.set(false);
            line1.set(false);
            line2.set(false);
            line4.set(false);
        }
        if (i == NO_FRISBEE_IN_BUCKET) {
            line0.set(true);
            line3.set(true);
            line1.set(false);
            line2.set(false);
            line4.set(false);
        }
        if (i == FRISBEE_IN_LOADER) {
            line1.set(true);
            line3.set(true);
            line0.set(false);
            line2.set(false);
            line4.set(false);
        }
        if (i == NO_FRISBEE_IN_LOADER) {
            line0.set(true);
            line1.set(true);
            line3.set(true);
            line2.set(false);
            line4.set(false);
        }
        if (i == TARGET_IN_SIGHT) {
            line2.set(true);
            line3.set(true);
            line0.set(false);
            line1.set(false);
            line4.set(false);
            driverLCD.println(displayLine, 2, "Target Lined Up ***SHOOT!!!!!");
            driverLCD.updateLCD();
        }
        if (i == TARGET_NOT_IN_SIGHT) {
            line0.set(true);
            line2.set(true);
            line3.set(true);
            line1.set(false);
            line4.set(false);
            driverLCD.println(displayLine, 2, "Target Not Visible ***REPOSITION");
            driverLCD.updateLCD();
        }
        if (i == AUTO_TARGETING) {
            line1.set(true);
            line2.set(true);
            line3.set(true);
            line0.set(false);
            line4.set(false);
            driverLCD.println(displayLine, 2, "Acquiring Target");
        }
        if (i == CLIMBING) {
            line0.set(true);
            line1.set(true);
            line2.set(true);
            line3.set(true);
            line4.set(false);
        }
        if (i == NO_CLIMB_SWITCHES_CLOSED) {
            line4.set(true);
            line0.set(false);
            line1.set(false);
            line2.set(false);
            line3.set(false);
        }
        if (i == LEFT_CLIMB_SWITCH_CLOSED) {
            line0.set(true);
            line4.set(true);
            line1.set(false);
            line2.set(false);
            line3.set(false);
        }
        if (i == RIGHT_CLIMB_SWITCH_CLOSED) {
            line1.set(true);
            line4.set(true);
            line0.set(false);
            line2.set(false);
            line3.set(false);
        }
        if (i == AUTONOMOUS_STARTED) {
            line0.set(true);
            line1.set(true);
            line4.set(true);
            line2.set(false);
            line3.set(false);
            
        }
        if (i == TELEOP_STARTED) {
            line2.set(true);
            line4.set(true);
            line0.set(false);
            line1.set(false);
            line3.set(false);
        }
        if (i == END_OF_MATCH) {
            line0.set(true);
            line2.set(true);
            line4.set(true);
            line1.set(false);
            line3.set(false);
        }
    }
}