// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.firebears.commands;

import edu.wpi.first.wpilibj.Gyro;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.image.ParticleAnalysisReport;
import org.firebears.Robot;
import org.firebears.RobotMap;
import org.firebears.subsystems.Camera;

/**
 * Turn toward the target most recently seen in the {@link Camera}. This should
 * be called after the {@link TakePicture} command. If no target was seen, the
 * command will finish without executing. Approaches the angle incrementally,
 * with no PID control.
 */
public class ChassisTurnToTarget extends Command {

    Gyro gyro = RobotMap.chassisGyro;
    Camera camera = Robot.camera;
    private ParticleAnalysisReport[] particleList = null;
    double goalAngle = 0;

    public ChassisTurnToTarget() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.chassis);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.camera);
    }
    // Called just before this Command runs the first time

    protected void initialize() {
        particleList = camera.getAllParticles();
        if (camera.hasPicture()) {
            goalAngle = camera.getAngle();
        } else {
            goalAngle = 0;
            System.out.println("No picture seen");
        }
        gyro.reset();
    }
    // Called repeatedly when this Command is scheduled to run

    protected void execute() {
        double currentAngle = Robot.chassis.getGyroAngle();
        if (currentAngle >= goalAngle + 1) {
            Robot.chassis.arcadeDrive(0, -.6);
        }
        if (currentAngle <= goalAngle - 1) {
            Robot.chassis.arcadeDrive(0, .6);
        }
    }
    // Make this return true when this Command no longer needs to run execute()

    protected boolean isFinished() {
        double currentAngle = Robot.chassis.getGyroAngle();
        if (currentAngle <= goalAngle + 1 && currentAngle >= goalAngle - 1) {
            return true;
        }
        return false;
    }
    // Called once after isFinished returns true

    protected void end() {
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run

    protected void interrupted() {
    }
}
