package org.firebears.commands;

import edu.wpi.first.wpilibj.command.PIDCommand;
import org.firebears.Robot;
import org.firebears.RobotMap;

/**
 * Rotate robot by a specific angle, using a PID controller.
 */
public class ChassisTurnToAngle extends PIDCommand {

    double goalAngle = 90.0;

    public ChassisTurnToAngle(double angle) {
        this();
        goalAngle = angle;
    }

    public ChassisTurnToAngle() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID
        super("ChassisTurnToAngle", 0.5, 0.0, 0.0, 0.02);
        getPIDController().setContinuous(true);
        getPIDController().setAbsoluteTolerance(1.0);
        getPIDController().setInputRange(-180.0, 180.0);
        getPIDController().setOutputRange(-0.6, 0.6);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.chassis);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    protected double returnPIDInput() {
        return Robot.chassis.getGyroAngle();
    }

    protected void usePIDOutput(double output) {
        Robot.chassis.arcadeDrive(0.0, output);
    }

    protected void initialize() {
        RobotMap.chassisGyro.reset();
        setSetpoint(goalAngle);
    }

    protected void execute() {
    }

    protected boolean isFinished() {
        return getPIDController().onTarget();
    }

    protected void end() {
        Robot.chassis.arcadeDrive(0.0, 0.0);
    }

    protected void interrupted() {
        end();
    }
}
