// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.firebears.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.firebears.Robot;
import org.firebears.RobotMap;
import org.firebears.subsystems.Lights;

/**
 *
 */
public class TriggerPush extends Command {
    final static double PUSH_TIME = RobotMap.PUSH_TIME;
    final static double PUSH_SPEED = RobotMap.PUSH_SPEED;
    final static double STOP = RobotMap.STOP;
    double PUSH = RobotMap.PUSH_TIME;
    //Subsystem shooter = Robot.shooter;

    public TriggerPush(double t) {
        requires(Robot.trigger);
        //TIME = t;
    }

    public TriggerPush() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.shooter);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRE
    }
    // Called just before this Command runs the first PUSH_TIME

    protected void initialize() {
        setTimeout(PUSH_TIME);
        Robot.lights.lightProgram(Lights.SHOOT);
        System.out.println("Push Timer Set");
    }
    // Called repeatedly when this Command is scheduled to run

    protected void execute() {
        //Robot.trigger
        Robot.trigger.TriggerMove(PUSH_SPEED);
    }
    // Make this return true when this Command no longer needs to run execute()

    protected boolean isFinished() {
        return isTimedOut();
    }
    // Called once after isFinished returns true

    protected void end() {
        Robot.trigger.TriggerMove(STOP);
        //Robot.trigger.reset();
        System.out.println("Push End");
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run

    protected void interrupted() {
        Robot.trigger.TriggerMove(STOP);
        //Robot.trigger.reset();
        System.out.println("Push Interrupted");
    }
}
